In [ ]:
import pandas as pd
import numpy as np
info = np.array(['P','A','V','A','N'])
a = pd.Series(info)
print(a)

0    P
1    A
2    V
3    A
4    N
dtype: object


In [ ]:
# a list of string
x = ['Pavan','Kalyan']
# Calling DataFrame constructor on list
df = pd.DataFrame(x)
print(df)

        0
0   Pavan
1  Kalyan


In [ ]:
# Pandas Series.map()
#Example: 1
import pandas as pd
import numpy as np
a = pd.Series(['Java', 'pycharm', 'jupiter','np.Pavan'])
a.map({'Java': 'Hello'})

0    Hello
1      NaN
2      NaN
3      NaN
dtype: object

In [ ]:
#Example: 2
import pandas as pd
import numpy as np
a = pd.Series(['Java', 'pycharm', 'jupiter', 'np.Pavan'])
a.map({'Java':'Hello'})
a.map('I Like {}'.format, na_action='ignore')

0        I Like Java
1     I Like pycharm
2     I Like jupiter
3    I Like np.Pavan
dtype: object

In [ ]:
# Pandas Series.to_frame()
# Example: 1
import pandas as pd
import numpy as np
a = pd.Series(["a","b","c"],
              name = "Pavan")
a.to_frame()

Pavan
0     a
1     b
2     c

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
emp = ["Pavan","Manjesh","Animess","Ankit","Pratik"]
id = [100,200,300,400,500]
salary = [10000,20000,30000,40000,50000]
emp_series = pd.Series(emp)
id_series=pd.Series(id)
salary_series = pd.Series(salary)
frame = {'Emp': emp_series, 'ID': id_series, 'Salary': salary_series}
result = pd.DataFrame(frame)
print(result)

       Emp   ID  Salary
0    Pavan  100   10000
1  Manjesh  200   20000
2  Animess  300   30000
3    Ankit  400   40000
4   Pratik  500   50000


In [ ]:
# importing the pandas library
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
# importing the pandas library
import pandas as pd
# a list of strings
x = ["Python", "Java", "C++"]
# Calling DataFrame constructor on list
df = pd.DataFrame(x)
print(df)

        0
0  Python
1    Java
2     C++


In [ ]:
# importing the pandas library
import pandas as pd
info = {"ID": [100, 200, 300, 400],"Department": ["B.sc", "M.sc", "B.sc", "M.sc"]}
df = pd.DataFrame(info)
print(df)

    ID Department
0  100       B.sc
1  200       M.sc
2  300       B.sc
3  400       M.sc


In [ ]:
# importing the pandas library
import pandas as pd

info = {"one": pd.Series([1, 2, 3, 4, 5], index = ["a", "b", "c", "d", "e"]),
        "two": pd.Series([10, 20, 30, 40, 50,60 ,70], index = ["a", "b", "c", "d", "e", "f", "h"])}
df = pd.DataFrame(info)
print(df)

   one  two
a  1.0   10
b  2.0   20
c  3.0   30
d  4.0   40
e  5.0   50
f  NaN   60
h  NaN   70


In [ ]:
# importing the pandas library
import pandas as pd
info = {"one": pd.Series([1, 2, 3, 4, 5], index = ["a", "b", "c", "d", "e"]),
        'two': pd.Series([10, 20, 30, 40, 50, 60, 70], index = ["a", "b", "c", "d", "e", "f", "h"])}
d1 = pd.DataFrame(info)
print(d1["one"])

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
h    NaN
Name: one, dtype: float64


In [ ]:
# importing the pandas library
import pandas as pd
info = {"one": pd.Series([1, 2, 3, 4, 5], index = ["a", "b", "c", "d", "e"]),
        'two': pd.Series([1,2,3,4,5,6], index = ["a", "b", "c", "d", "e", "f"])}
df = pd.DataFrame(info)
# Add a new column to an existing DataFrame object
print("Adding a new column by passing as Series:")
df['three']= pd.Series([100, 200, 300, 400, 500], index = ["a", "b", "c", "d", "e"])
print(df)
print("Adding a new column using existing DataFrame columns")
df['four']= df['one']+df['three']
print(df)

Adding a new column by passing as Series:
   one  two  three
a  1.0    1  100.0
b  2.0    2  200.0
c  3.0    3  300.0
d  4.0    4  400.0
e  5.0    5  500.0
f  NaN    6    NaN
Adding a new column using existing DataFrame columns
   one  two  three   four
a  1.0    1  100.0  101.0
b  2.0    2  200.0  202.0
c  3.0    3  300.0  303.0
d  4.0    4  400.0  404.0
e  5.0    5  500.0  505.0
f  NaN    6    NaN    NaN


In [ ]:
# importing the pandas library
import pandas as pd
info = {'one': pd.Series([1,2], index=['a','b']),
        'two': pd.Series([1,2,3], index=['a','b','c'])}
df = pd.DataFrame(info)
print("The DataFrame:")
print(df)
# using del function
print("Deleting the first column:")
del df['one']
print(df)
# using pop function
print("Deleting the another column:")
df.pop('two')
print(df)

The DataFrame:
   one  two
a  1.0    1
b  2.0    2
c  NaN    3
Deleting the first column:
   two
a    1
b    2
c    3
Deleting the another column:
Empty DataFrame
Columns: []
Index: [a, b, c]


In [ ]:
# importing he pandas library
import pandas as pd
info = {'one': pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd']),
        'two': pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])}
df = pd.DataFrame(info)
print(df.iloc[2])

one    3.0
two    3.0
Name: c, dtype: float64


In [ ]:
# importing the pandas library
import pandas as pd
info = {'one': pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd','e']),
        'two': pd.Series([1,2,3,4,5,6], index=['a','b','c','d','e','f'])}
df = pd.DataFrame(info)
print(df[2:5])

   one  two
c  3.0    3
d  4.0    4
e  5.0    5


In [ ]:
# importing the panadas library
import pandas as pd
d = pd.DataFrame([[1,2],[3,4]], columns=['x','y'])
d2 = pd.DataFrame([[5,6],[7,8]], columns=['x','y'])
d = d.append(d2)
print(d)

   x  y
0  1  2
1  3  4
0  5  6
1  7  8


<ipython-input-37-050a74d857c9>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  d = d.append(d2)


In [ ]:
# importing the pandas as pd
import pandas as pd
a_info = pd.DataFrame([[1,2],[3,4]], columns=['x','y'])
b_info = pd.DataFrame([[5,6],[7,8]], columns=['x','y'])
a_info = a_info.append(b_info)
# Drop rows with label 0
a_info = a_info.drop(0)
print(a_info)
print(b_info)

   x  y
1  3  4
1  7  8
   x  y
0  5  6
1  7  8


<ipython-input-42-d0367e013d07>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a_info = a_info.append(b_info)


In [ ]:
# importing the 'array' for demonstrating array operations
import array
# initializing an array with array values and signed integers
arr = array.array('l', [2,4,6,8,10,12])
# print the original array
print("New created array:" , end=" ")
for l in range (0,5):
  print(arr[l], end=" ")
print("\r")

New created array: 2 4 6 8 10 


In [ ]:
# Example 1
# importing pandas as pd
import pandas as pd
# dictionary of lists
dict = {"name":["Pavan", "Kalyan", "Manjesh", "Animesh"],
'age':["18","18","17", "18"]}
info = pd.DataFrame(dict, index = [True,True, False, True])
print(info)

          name age
True     Pavan  18
True    Kalyan  18
False  Manjesh  17
True   Animesh  18


In [ ]:
# Example 2
# importing pandas as pd
import pandas as pd
# dictionary of lists
dict = {"name":["Ramu", "Rohit", "Bheem Rao", "Pulaji"],
'age':["19","18","20", "18"]}
info = pd.DataFrame(dict, index = [True,True, False, True])
# accessing a dataframe using .loc[] function
print(info.loc[True])

        name age
True    Ramu  19
True   Rohit  18
True  Pulaji  18


In [ ]:
import numpy as np
arr = np.arange(16)
print("The Original array is: \n", arr)
# shape array with 2 rows and 8 columns
arr = np.arange(16).reshape(2,8)
print("\nreshapedarray: \n", arr)
# shape array with 2 rows and 8 columns
arr = np.arange(16).reshape(8,2)
print("\nreshaped array: \n", arr)

The Original array is: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshapedarray: 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)
b =np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
import numpy as np
a = np.zeros((2,2))
print(a)
b = np.ones((2,2))
print(b)
c = np.full((2,2), 7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.61094963 0.63648175]
 [0.40508201 0.96890463]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
print(a[0,1])
b[0,0] = 77
a[0,1]
print(a[0,1])

2
77


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_r1 = a[1,:]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2], [0,1,0]])
print(np.array([a[0,0], a[1,1], a[2,0]]))
print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])
a[np.arange(4), b] += 10
print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4], [5,6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [ ]:
#DataTypes
import numpy as np
x = np.array([1, 2])
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)


int64
float64
int64


In [ ]:
#Array math
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
#Dot function
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
print(v.dot(w))
print(np.dot(v, w))
print(x.dot(v))
print(np.dot(x, v))
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [5]:
import numpy as np
x = np.array([[1,2], [3,4]])
print(np.sum(x))
print(np.sum(x, axis =0))
print(np.sum(x, axis =1))

10
[4 6]
[3 7]


In [9]:
import numpy as np
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)
v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
